default:

    # estimated relative growth size of R memory relative to block size
    R_memory_bloat          : 1.5
    # reference machine configuration
    reference_machine       :
        ncores              :  16
        datasize            :   3
        memsize             :  64
        nsamples            :  2000
        time_read           :  30
        virtual_fs          :  2.5
        time_process        :  7.0

    # adjustment shift
    default_adjustment_shift        : 100.0

    # estimated proportion of time used to process

    # Protocols accepted for data acess
    protocols               : ["WTSS", "SATVEG", "RASTER"]
    # Time series services known to SITS
    ts_services             : ["WTSS-INPE", "SATVEG", "RASTER"]
    # Names of ts_services per protocols
    WTSS_services           : ["WTSS-INPE"]
    SATVEG_services         : ["SATVEG"]
    RASTER_protocol         : ["RASTER"]

    # URL to access each WTSS service

    WTSS-INPE_protocol      : "WTSS"
    WTSS-INPE_server        : "http://www.esensing.dpi.inpe.br/wtss/"

    # URL to access SATVEG
    SATVEG_protocol         : "SATVEG"
    SATVEG_server           : "https://www.satveg.cnptia.embrapa.br/satvegws/ws/perfil/ZW46IXzr4pRzJlX/"
    SATVEG_coverages        : ["terra", "aqua", "comb"]

    SATVEG_bands            :
        terra               : &bands-sv ["ndvi", "evi"]
        aqua                : *bands-sv
        comb                : *bands-sv
    SATVEG_bbox             :
        terra               :
            xmin            : &xmin_satveg -81.2341
            xmax            : &xmax_satveg -31.9165
            ymin            : &ymin_satveg -30.0000
            ymax            : &ymax_satveg  10.000
        aqua                :
            xmin            : *xmin_satveg
            xmax            : *xmax_satveg
            ymin            : *ymin_satveg
            ymax            : *ymax_satveg
        comb                :
            xmin            : *xmin_satveg
            xmax            : *xmax_satveg
            ymin            : *ymin_satveg
            ymax            : *ymax_satveg
    SATVEG_size             :
        terra               :
            nrows           : &nrows_satveg 24000
            ncols           : &ncols_satveg 19200
        aqua                :
            nrows           : *nrows_satveg
            ncols           : *ncols_satveg
        comb                :
            nrows           : *nrows_satveg
            ncols           : *ncols_satveg
    SATVEG_prefilter        :
        terra               : &prefilter ["0", "1", "2", "3"] # "0" - none, "1" - no data correction, "2" - cloud correction, "3" - no data and cloud correction
        aqua                : *prefilter
        comb                : *prefilter
    SATVEG_crs              :
        terra               : &crs-wgs84 "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
        aqua                : *crs-wgs84
        comb                : *crs-wgs84

    SATVEG_resolution:
        terra               :
            xres            : &mod13q1-x 0.00208334
            yres            : &mod13q1-y 0.00208334
        aqua                :
            xres            : *mod13q1-x
            yres            : *mod13q1-y

        comb                :
            xres            : *mod13q1-x
            yres            : *mod13q1-y

    SATVEG_missing_value:
        terra               :
            ndvi            : &ndvi-mv  -3000
            evi             : &evi-mv   -3000
        aqua                :
            ndvi            : *ndvi-mv
            evi             : *evi-mv
        comb                :
            ndvi            : *ndvi-mv
            evi             : *evi-mv

    SATVEG_scale_factor:
        terra               :
            ndvi            : &ndvi-sf 0.0001
            evi             : &evi-sf  0.0001
        aqua                :
            ndvi            : *ndvi-sf
            evi             : *evi-sf
        comb                :
            ndvi            : *ndvi-sf
            evi             : *evi-sf

    RASTER_missing_value:
        MODIS               :
            ndvi            : -3000
            evi             : -3000
            red             : -1000
            nir             : -1000
            blue            : -1000
            mir             : -1000
        LANDSAT             :
            ndvi            : -9999
            evi             : -9999
            red             : -9999
            nir             : -9999
            swir1           : -9999
            swir2           : -9999

    RASTER_minimum_value    :
        ndvi                : -3000
        evi                 : -3000
        red                 : 0
        blue                : 0
        nir                 : 0
        mir                 : 0

    RASTER_scale_factor:
        MODIS               :
            ndvi            : 0.0001
            evi             : 0.0001
            red             : 0.0001
            nir             : 0.0001
            blue            : 0.0001
            mir             : 0.0001
        LANDSAT             :
            ndvi            : 0.0001
            evi             : 0.0001
            red             : 0.0001
            nir             : 0.0001
            mir             : 0.0001
            swir1           : 0.0001
            swir2           : 0.0001

    RASTER_resolution:
        MODIS               :
            xres            : 0.00208334
            yres            : 0.00208334

    tasseled_cap_coef       :
        MODIS               :
            brightness      :
                 red        : 0.4395
                 nir        : 0.5495
                 blue       : 0.2460
                 green      : 0.3918
                 nir2       : 0.3506
                 mir1       : 0.3506
                 mir        : 0.2678
            greenness       :
                 red        : -0.4064
                 nir        :  0.5129
                 blue       : -0.2744
                 green      : -0.2893
                 nir2       :  0.4882
                 mir1       : -0.036
                 mir        : -0.4169

            wetness         :
                 red        : -0.4064
                 nir        :  0.5129
                 blue       : -0.2744
                 green      : -0.2893
                 nir2       :  0.4882
                 mir1       : -0.036
                 mir        : -0.4169

        LANDSAT8            :
            brightness      :
                 blue       : 0.3029
                 green      : 0.2786
                 red        : 0.4733
                 nir        : 0.5599
                 swir1      : 0.508
                 swir2      : 0.1872

            greenness       :
                 blue       : -0.2941
                 green      : -0.243
                 red        : -0.5424
                 nir        :  0.7276
                 swir1      :  0.0713
                 swir2      : -0.1608

            wetness         :
                 blue       :  0.1511
                 green      :  0.1973
                 red        :  0.3283
                 nir        :  0.3407
                 swir1      : -0.7117
                 swir2      : -0.4559

    RASTER_timeline :
        MOD13Q1     : [ "2000-02-18", "2000-03-05", "2000-03-21", "2000-04-06", "2000-04-22", "2000-05-08", "2000-05-24", 2000-06-09",
                        "2000-06-25", "2000-07-11", "2000-07-27", "2000-08-12", "2000-08-28", "2000-09-13", "2000-09-29", "2000-10-15",
                        "2000-10-31", "2000-11-16", "2000-12-02", "2000-12-18", "2001-01-01", "2001-01-17", "2001-02-02", "2001-02-18",
                        "2001-03-06", "2001-03-22", "2001-04-07", "2001-04-23", "2001-05-09", "2001-05-25", "2001-06-10", "2001-06-26",
                        "2001-07-12", "2001-07-28", "2001-08-13", "2001-08-29", "2001-09-14", "2001-09-30", "2001-10-16", "2001-11-01",
                        "2001-11-17", "2001-12-03", "2001-12-19", "2002-01-01", "2002-01-17", "2002-02-02", "2002-02-18", "2002-03-06",
                        "2002-03-22", "2002-04-07", "2002-04-23", "2002-05-09", "2002-05-25", "2002-06-10", "2002-06-26", "2002-07-12",
                        "2002-07-28", "2002-08-13", "2002-08-29", "2002-09-14", "2002-09-30", "2002-10-16", "2002-11-01", "2002-11-17",
                        "2002-12-03", "2002-12-19", "2003-01-01", "2003-01-17", "2003-02-02", "2003-02-18", "2003-03-06", "2003-03-22",
                        "2003-04-07", "2003-04-23", "2003-05-09", "2003-05-25", "2003-06-10", "2003-06-26", "2003-07-12", "2003-07-28",
                        "2003-08-13", "2003-08-29", "2003-09-14", "2003-09-30", "2003-10-16", "2003-11-01", "2003-11-17", "2003-12-03",
                        "2003-12-19", "2004-01-01", "2004-01-17", "2004-02-02", "2004-02-18", "2004-03-05", "2004-03-21", "2004-04-06",
                        "2004-04-22", "2004-05-08", "2004-05-24", "2004-06-09", "2004-06-25", "2004-07-11", "2004-07-27", "2004-08-12",
                        "2004-08-28", "2004-09-13", "2004-09-29", "2004-10-15", "2004-10-31", "2004-11-16", "2004-12-02", "2004-12-18",
                        "2005-01-01", "2005-01-17", "2005-02-02", "2005-02-18", "2005-03-06", "2005-03-22", "2005-04-07", "2005-04-23",
                        "2005-05-09", "2005-05-25", "2005-06-10", "2005-06-26", "2005-07-12", "2005-07-28", "2005-08-13", "2005-08-29",
                        "2005-09-14", "2005-09-30", "2005-10-16", "2005-11-01", "2005-11-17", "2005-12-03", "2005-12-19", "2006-01-01",
                        "2006-01-17", "2006-02-02", "2006-02-18", "2006-03-06", "2006-03-22", "2006-04-07", "2006-04-23", "2006-05-09",
                        "2006-05-25", "2006-06-10", "2006-06-26", "2006-07-12", "2006-07-28", "2006-08-13", "2006-08-29", "2006-09-14",
                        "2006-09-30", "2006-10-16", "2006-11-01", "2006-11-17", "2006-12-03", "2006-12-19", "2007-01-01", "2007-01-17",
                        "2007-02-02", "2007-02-18", "2007-03-06", "2007-03-22", "2007-04-07", "2007-04-23", "2007-05-09", "2007-05-25",
                        "2007-06-10", "2007-06-26", "2007-07-12", "2007-07-28", "2007-08-13", "2007-08-29", "2007-09-14", "2007-09-30",
                        "2007-10-16", "2007-11-01", "2007-11-17", "2007-12-03", "2007-12-19", "2008-01-01", "2008-01-17", "2008-02-02",
                        "2008-02-18", "2008-03-05", "2008-03-21", "2008-04-06", "2008-04-22", "2008-05-08", "2008-05-24", "2008-06-09",
                        "2008-06-25", "2008-07-11", "2008-07-27", "2008-08-12", "2008-08-28", "2008-09-13", "2008-09-29", "2008-10-15",
                        "2008-10-31", "2008-11-16", "2008-12-02", "2008-12-18", "2009-01-01", "2009-01-17", "2009-02-02", "2009-02-18",
                        "2009-03-06", "2009-03-22", "2009-04-07", "2009-04-23", "2009-05-09", "2009-05-25", "2009-06-10", "2009-06-26",
                        "2009-07-12", "2009-07-28", "2009-08-13", "2009-08-29", "2009-09-14", "2009-09-30", "2009-10-16", "2009-11-01",
                        "2009-11-17", "2009-12-03", "2009-12-19", "2010-01-01", "2010-01-17", "2010-02-02", "2010-02-18", "2010-03-06",
                        "2010-03-22", "2010-04-07", "2010-04-23", "2010-05-09", "2010-05-25", "2010-06-10", "2010-06-26", "2010-07-12",
                        "2010-07-28", "2010-08-13", "2010-08-29", "2010-09-14", "2010-09-30", "2010-10-16", "2010-11-01", "2010-11-17",
                        "2010-12-03", "2010-12-19", "2011-01-01", "2011-01-17", "2011-02-02", "2011-02-18", "2011-03-06", "2011-03-22",
                        "2011-04-07", "2011-04-23", "2011-05-09", "2011-05-25", "2011-06-10", "2011-06-26", "2011-07-12", "2011-07-28",
                        "2011-08-13", "2011-08-29", "2011-09-14", "2011-09-30", "2011-10-16", "2011-11-01", "2011-11-17", "2011-12-03",
                        "2011-12-19", "2012-01-01", "2012-01-17", "2012-02-02", "2012-02-18", "2012-03-05", "2012-03-21", "2012-04-06",
                        "2012-04-22", "2012-05-08", "2012-05-24", "2012-06-09", "2012-06-25", "2012-07-11", "2012-07-27", "2012-08-12",
                        "2012-08-28", "2012-09-13", "2012-09-29", "2012-10-15", "2012-10-31", "2012-11-16", "2012-12-02", "2012-12-18",
                        "2013-01-01", "2013-01-17", "2013-02-02", "2013-02-18", "2013-03-06", "2013-03-22", "2013-04-07", "2013-04-23",
                        "2013-05-09", "2013-05-25", "2013-06-10", "2013-06-26", "2013-07-12", "2013-07-28", "2013-08-13", "2013-08-29",
                        "2013-09-14", "2013-09-30", "2013-10-16", "2013-11-01", "2013-11-17", "2013-12-03", "2013-12-19", "2014-01-01",
                        "2014-01-17", "2014-02-02", "2014-02-18", "2014-03-06", "2014-03-22", "2014-04-07", "2014-04-23", "2014-05-09",
                        "2014-05-25", "2014-06-10", "2014-06-26", "2014-07-12", "2014-07-28", "2014-08-13", "2014-08-29", "2014-09-14",
                        "2014-09-30", "2014-10-16", "2014-11-01", "2014-11-17", "2014-12-03", "2014-12-19", "2015-01-01", "2015-01-17",
                        "2015-02-02", "2015-02-18", "2015-03-06", "2015-03-22", "2015-04-07", "2015-04-23", "2015-05-09", "2015-05-25",
                        "2015-06-10", "2015-06-26", "2015-07-12", "2015-07-28", "2015-08-13", "2015-08-29", "2015-09-14", "2015-09-30",
                        "2015-10-16", "2015-11-01", "2015-11-17", "2015-12-03", "2015-12-19", "2016-01-01", "2016-01-17", "2016-02-02",
                        "2016-02-18", "2016-03-05", "2016-03-21", "2016-04-06", "2016-04-22", "2016-05-08", "2016-05-24", "2016-06-09",
                        "2016-06-25", "2016-07-11", "2016-07-27", "2016-08-12", "2016-08-28", "2016-09-13", "2016-09-29", "2016-10-15",
                        "2016-10-31", "2016-11-16", "2016-12-02", "2016-12-18", "2017-01-01", "2017-01-17", "2017-02-02", "2017-02-18",
                        "2017-03-06", "2017-03-22", "2017-04-07", "2017-04-23", "2017-05-09", "2017-05-25", "2017-06-10", "2017-06-26",
                        "2017-07-12", "2017-07-28", "2017-08-13", "2017-08-29", "2017-08-14", "2017-09-30", "2017-10-16", "2017-11-01",
                        "2017-11-17", "2017-12-03" ]

    colors:
        Araguaia :          "#78c679"
        Beans :             "#8c96c6"
        Campo_Cerrado :     "#addd8e"
        Cerradao     :      "#238443"
        Cerrado :           "#41ab5d"
        Cerrado_Rupestre :  "#d9f0a3"
        Corn :              "#fcbba1"
        Cotton:             "#fb6a4a"
        Dunas :             "#fff7e6"
        Fallow_Cotton :     "#fb6a4a"
        Millet_Cotton :     "#fb6a4a"
        Forest :            "#006837"
        Pasture :           "#c6dbef"
        Soy_Corn :          "#993404"
        Soy_Cotton :        "#662506"
        Soy_Fallow :        "#fec44f"
        Soy_Sorghum:        "#ec7014"
        Soy_Millet :        "#ec7014"
        Soy_Sunflower :     "#fe9929"
        Sugarcane :         "#8c6bb1"
        Urban_Area :        "#969696"
        Urban Area :        "#969696"
        Water      :        "#00008b"




